### ISSUE TITLE
Mantra patterns with multiple themes

### ISSUE THREAD

**Issue by EcstasyEngineer** [EcstasyEngineer/ai-conditioner#3]
left, and right can be any combination of single-pattern(A), single-pattern(B), or single-pattern(A∩B), with the one exception the left and right cant be the same theme (unless both are intersection.

examples:
Left: pattern(A), Right: Pattern(B)
Left: Pattern(B), Right: Pattern(A)
Left: Pattern(A), Right: Pattern(A∩B)
Left: Pattern(A∩B), Right: Pattern(A)
Left: Pattern(B), Right: Pattern(A∩B)
Left: Pattern(A∩B), Right: Pattern(B)

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the generate_session function to allow different theme patterns for left and right audio channels. Added new input parameters for left and right themes, and updated the line selection logic to accommodate these changes.

You can review changes in this commit: https://github.com/lkilu6456546/EcstasyEngineer-ai-conditioner-3/commit/334187386b413f5a988f52acbe4b70b1529960c8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by EcstasyEngineer** [comment]
this is now available with the LayeredPlayer https://github.com/EcstasyEngineer/ai-conditioner/blob/main/src/cyclers_and_players_overview.md
